### PR TITLE
*New changes to COBALT for ESM4.2

### PR DESCRIPTION
**Pull request by jessluo**
Changes from @charliestock and myself:
1) Bug fixes in the nitrification production calculation to close the alkalinity budget
2) Increases in phosphorus burial to prevent phosphorus accumulation in the pre-industrial control
3) Improve chlorophyll in subtropical gyres by reducing small phytoplankton basal respiration
4) Reductions in calcite and aragonite production (after previous increase)

Also balanced the calcite burial using these modified settings for the xml:
```
"OCN", "runoff_alk_flux_ice_ocn",  "",    "",                             "none",  0.294e-3
"OCN", "runoff_dic_flux_ice_ocn",  "",    "",                             "none",  0.253e-3
```

### CODE REVIEW

**Comment by nikizadehgfdl** [comment]
Changes answers, right?

**Review by nikizadehgfdl — APPROVED** [review]

**Comment by jessluo** [comment]
yes, these code modifications change answers.

**Comment by nikizadehgfdl** [comment]
I prepended the title with  *  to remind us this changes answers.

**Comment by nikizadehgfdl** [comment]
@charliestock could you take a look at the changes in this PR to ensure all that is needed for ESM4.2 is in? Thanks.

**Pull request merged**
